### ISSUE TITLE
Provide a release tarball

### ISSUE THREAD

**Issue by fcambus** [mpeterv/markdown#2]
It would be nice if you would consider adding proper source release tarballs,
as GitHub auto-generated tarballs are not immutable. This is an issue [1] for
operating systems creating packages for lua-markdown. Thanks in advance.

[1] https://marc.info/?l=openbsd-ports&m=151973450514279&w=2

**Comment by mpeterv** [comment]
I assume getting sources for a release directly from git is not feasible? Should the tarball contain anything in addition to `LICENSE` and `markdown.lua`?

**Comment by fcambus** [comment]
Indeed, getting the sources from Git directly is not feasible.

Regarding the tarball, it doesn't need anything more than what is currently packaged in the [auto-generated file](https://github.com/mpeterv/markdown/archive/0.33.tar.gz).

You can simply upload markdown-0.33.tar.gz as a release asset, to ensure the file is immutable.

**Comment by tst2005** [comment]
You should maybe try to solve your problem with auto-generated file instead of ask to all projects to host a file ?
* download the autogenerated file
* remove the timestamp (or some metadata that change all the time) to a stable one
* make a checksum of this tarball
Or
* "try to" contact github to spoke about this problem ...
Or
* host your own immutable tarball in one github repository ...
Or
* support git to download source directly
* with or without the tag signature

It seems annoying to ask everybody to host a static file... and do it again for each new version, right ?

EDIT: do you have a page or repo to explain what is the problem with github auto-generated file ? i still don't understand what is the real issue.
Regards
